// client/src/presentation/components/Footer/Footer.tsx
import React from 'react';
import styles from './Footer.module.css';

const Footer = () => {
    return (
        <footer className={styles.footer}>
            <div className={styles.footerColumn}>
                <h3>About Us</h3>
                <p>
                    We are dedicated to providing the best service in the industry. Our mission is to
                    exceed your expectations and deliver exceptional value.
                </p>
            </div>
            <div className={styles.footerColumn}>
                <h3>Contact Information</h3>
                <p>Address: 123 Main St, Your City, Your Country</p>
                <p>Phone: (123) 456-7890</p>
                <p>Email: info@yourcompany.com</p>
            </div>
            <div className={styles.footerColumn}>
                <h3>Social Media Links</h3>
                <ul className={styles.socialMedia}>
                    <li><img src={"https://upload.wikimedia.org/wikipedia/commons/5/51/Facebook_f_logo_%282019%29.svg"} alt={''}/> <a href="#" className={styles.socialIcon}>Facebook</a></li>
                    <li><img src={"https://img.freepik.com/free-vector/new-2023-twitter-logo-x-icon-design_1017-45418.jpg?w=1060&t=st=1728017452~exp=1728018052~hmac=9b9d6ea2c97b0e950fd008f1f101552227445c592e37625338c9201229de16f7"} alt={''}/> <a href="#" className={styles.socialIcon}>Twitter</a></li>
                    <li><img src={"https://upload.wikimedia.org/wikipedia/commons/a/a5/Instagram_icon.png"} alt={''}/> <a href="#" className={styles.socialIcon}>Instagram</a></li>
                </ul>
            </div>
            <div className={styles.footerColumn}>
                <h3>Legal Information</h3>
                <ul className={styles.legalLinks}>
                    <li><a href="#">Terms of Service</a></li>
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Legal Disclaimer</a></li>
                </ul>
            </div>
        </footer>
    );
};

export default Footer;

// frontend/project/src/app/footer/footer.component.ts
import { Component } from '@angular/core';
import {NzColDirective, NzRowDirective} from "ng-zorro-antd/grid";

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [
    NzRowDirective,
    NzColDirective
  ],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss'
})
export class FooterComponent {

}

<footer nz-row nzGutter="16" class="footer">
  <div nz-col nzSpan="6" class="footer-section">
    <h3>About Us</h3>
    <p>Brief description of our company and mission.</p>
  </div>

  <div nz-col nzSpan="6" class="footer-section">
    <h3>Contact Information</h3>
    <p>Address: 123 Main St, Your City, Your Country</p>
    <p>Phone: (123) 456-7890</p>
    <p>Email: infoyourcompany.com</p>
  </div>

  <div nz-col nzSpan="6" class="footer-section">
    <h3>Social Media Links</h3>
    <a href="https://www.facebook.com" target="_blank">Facebook</a><br />
    <a href="https://www.twitter.com" target="_blank">Twitter</a><br />
    <a href="https://www.instagram.com" target="_blank">Instagram</a>
  </div>

  <div nz-col nzSpan="6" class="footer-section">
    <h3>Legal Information</h3>
    <a href="/terms-of-service" target="_blank">Terms of Service</a><br />
    <a href="/privacy-policy" target="_blank">Privacy Policy</a><br />
    <a href="/disclaimer" target="_blank">Legal Disclaimer</a>
  </div>
</footer>
